apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - ../../secrets/aws-secretstore.yaml
  - ../../secrets/external-secret-prod.yaml

namePrefix: prod-

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
