apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common
  - secret.yaml

namePrefix: prod-

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml
