apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rag-secrets
  namespace: rag-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: rag-secrets
    template:
      type: Opaque
      data: # variables will be replaced by secrets from secret store
        NEO4J_USER: "{{ .NEO4J_USER }}"
        NEO4J_PASSWORD: "{{ .NEO4J_PASSWORD }}"
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
  data:     # map AWS Secrets Manager keys to local keys
    - secretKey: NEO4J_USER
      remoteRef:
        key: neo4j/prod/user
    - secretKey: NEO4J_PASSWORD
      remoteRef:
        key: neo4j/prod/password
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: openai/prod/api-key
