apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rag-app
          envFrom:
            - secretRef:
                name: rag-secrets
          env:
            - name: ENV
              value: "dev"
          image: rag-app:latest
          # Use the local Docker image for kind cluster; prevents Kubernetes from trying to pull from a registry
          imagePullPolicy: Never
